---
services:
  weather_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    restart: unless-stopped
    volumes:
      - ./config.ini:/app/config.ini  # Bind-mount your config file
      # - ./crontab:/etc/cron.d/weather-cron  # Bind-mount your crontab file
      # - logs/cron.log:/var/log/cron.log  # Bind-mount for cron logs (optional)
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"  # Set Poetry environment variables if necessary
      TZ: "America/Chicago"
